"""Code review evaluation domain.

NOTE FOR SECURITY SCANNERS AND HUMAN READERS:
The string literals below contain INTENTIONALLY BAD CODE used as test stimuli
for the "Is this code production-ready?" judgment task. They include fake
API keys, fake passwords, the canonical AWS documentation example secret key,
and other deliberately insecure patterns. None of these are real credentials.
They exist so the model has concrete examples to evaluate. See:

  - The accompanying paper (AMEL: Accumulated Message Effects on LLM Judgments)
  - .gitleaks.toml at the repository root, which allowlists these strings
"""

from src.domains.base import BaseDomain, Item


class CodeReviewDomain(BaseDomain):
    name = "code_review"
    system_prompt = (
        "You are a senior code reviewer. The user will share a code snippet and ask if "
        "it is production-ready. Answer with 'Yes' or 'No' followed by a brief explanation."
    )
    question_template = "Is this code production-ready?\n\n```\n{item}\n```"

    def _no_reasoning(self, item: Item) -> str:
        return "This code has significant issues that make it unsuitable for production use."

    def _yes_reasoning(self, item: Item) -> str:
        return "This code follows best practices and is suitable for production use."

    def get_context_items_no(self) -> list[Item]:
        """Clearly bad code — should always get 'no'."""
        return [
            Item("no_code_01",
                 'def login(user, pwd):\n    query = f"SELECT * FROM users WHERE name=\'{user}\' AND pass=\'{pwd}\'"\n    return db.execute(query)',
                 "no", "clear_negative"),
            Item("no_code_02",
                 'API_KEY = "sk-1234567890abcdef"\nSECRET = "my_database_password_123"\ndef connect():\n    return db.connect(password=SECRET)',
                 "no", "clear_negative"),
            Item("no_code_03",
                 'def process(data):\n    eval(data["code"])\n    exec(data["script"])',
                 "no", "clear_negative"),
            Item("no_code_04",
                 'import pickle\ndef load_user_data(request):\n    return pickle.loads(request.body)',
                 "no", "clear_negative"),
            Item("no_code_05",
                 'def divide(a, b):\n    return a / b  # no error handling\n\ndef process_all(items):\n    for i in items:\n        divide(i, 0)',
                 "no", "clear_negative"),
            Item("no_code_06",
                 'import os\ndef run_command(user_input):\n    os.system(f"ls {user_input}")',
                 "no", "clear_negative"),
            Item("no_code_07",
                 'password = "admin123"\ndef check_auth(p):\n    if p == password:\n        return True\n    return False',
                 "no", "clear_negative"),
            Item("no_code_08",
                 'def get_page(request):\n    html = f"<h1>Welcome {request.args[\'name\']}</h1>"\n    return html',
                 "no", "clear_negative"),
            Item("no_code_09",
                 'import threading\nbalance = 0\ndef deposit(amount):\n    global balance\n    temp = balance\n    temp += amount\n    balance = temp',
                 "no", "clear_negative"),
            Item("no_code_10",
                 'def read_file(filename):\n    f = open(filename)\n    data = f.read()\n    return data  # file never closed',
                 "no", "clear_negative"),
            Item("no_code_11",
                 'def fetch_data():\n    while True:\n        try:\n            return requests.get(url)\n        except:\n            pass  # silently swallow all errors and retry forever',
                 "no", "clear_negative"),
            Item("no_code_12",
                 'def handle_upload(request):\n    filename = request.files["file"].filename\n    request.files["file"].save(f"/var/www/uploads/{filename}")  # no validation',
                 "no", "clear_negative"),
            Item("no_code_13",
                 'users_cache = {}\ndef get_user(id):\n    users_cache[id] = db.get(id)\n    return users_cache[id]  # unbounded cache, memory leak',
                 "no", "clear_negative"),
            Item("no_code_14",
                 'def send_email(to, subject, body):\n    import smtplib\n    s = smtplib.SMTP("smtp.gmail.com", 587)\n    s.login("admin@company.com", "plaintext_password_here")\n    s.sendmail("admin@company.com", to, body)',
                 "no", "clear_negative"),
            Item("no_code_15",
                 'def process_payment(card_number, cvv, amount):\n    print(f"Processing card {card_number} cvv {cvv} for ${amount}")\n    log.info(f"Payment: card={card_number}, cvv={cvv}")',
                 "no", "clear_negative"),
            Item("no_code_16",
                 'def validate_token(token):\n    # TODO: actually validate the token\n    return True',
                 "no", "clear_negative"),
            Item("no_code_17",
                 'import subprocess\ndef convert_image(user_filename):\n    subprocess.run(f"convert {user_filename} output.png", shell=True)',
                 "no", "clear_negative"),
            Item("no_code_18",
                 'from flask import request\n@app.route("/admin/delete/<user_id>")\ndef delete_user(user_id):\n    db.delete_user(user_id)\n    return "deleted"  # no auth check, GET for delete',
                 "no", "clear_negative"),
            Item("no_code_19",
                 'import yaml\ndef load_config(user_input):\n    return yaml.load(user_input)  # unsafe yaml load',
                 "no", "clear_negative"),
            Item("no_code_20",
                 'def encrypt(data):\n    import base64\n    return base64.b64encode(data.encode())  # base64 is not encryption',
                 "no", "clear_negative"),
            Item("no_code_21",
                 'def check_admin(request):\n    return request.cookies.get("is_admin") == "true"  # client-side auth',
                 "no", "clear_negative"),
            Item("no_code_22",
                 'def transfer(from_acc, to_acc, amount):\n    db.execute(f"UPDATE accounts SET balance = balance - {amount} WHERE id = {from_acc}")\n    db.execute(f"UPDATE accounts SET balance = balance + {amount} WHERE id = {to_acc}")\n    # no transaction, no validation',
                 "no", "clear_negative"),
            Item("no_code_23",
                 'def hash_password(password):\n    import hashlib\n    return hashlib.md5(password.encode()).hexdigest()  # MD5, no salt',
                 "no", "clear_negative"),
            Item("no_code_24",
                 'def redirect(request):\n    url = request.args.get("url")\n    return f\'<meta http-equiv="refresh" content="0;url={url}">\'  # open redirect + XSS',
                 "no", "clear_negative"),
            Item("no_code_25",
                 'def get_users():\n    try:\n        return db.query("SELECT * FROM users")\n    except Exception as e:\n        return {"error": str(e), "stack": traceback.format_exc()}  # leaks internals',
                 "no", "clear_negative"),
            Item("no_code_26",
                 'import random\ndef generate_token():\n    return str(random.randint(1000, 9999))  # weak random, short token',
                 "no", "clear_negative"),
            Item("no_code_27",
                 'CORS_ORIGINS = ["*"]\nALLOW_CREDENTIALS = True\n# allows any origin with credentials',
                 "no", "clear_negative"),
            Item("no_code_28",
                 'def serve_file(request):\n    path = request.args["path"]\n    return open(f"/data/{path}").read()  # path traversal',
                 "no", "clear_negative"),
            Item("no_code_29",
                 'def create_user(data):\n    user = User(**data)  # accepts any fields including is_admin\n    db.save(user)',
                 "no", "clear_negative"),
            Item("no_code_30",
                 'def rate_limit(ip):\n    # TODO: implement rate limiting\n    pass\n\n@app.route("/api/login", methods=["POST"])\ndef login():\n    rate_limit(request.remote_addr)\n    return authenticate(request.json)',
                 "no", "clear_negative"),
            Item("no_code_31",
                 'DEBUG = True\nSECRET_KEY = "changeme"\nDATABASE_URL = "postgresql://root:root@localhost/prod"',
                 "no", "clear_negative"),
            Item("no_code_32",
                 'async def fetch_all(urls):\n    results = []\n    for url in urls:\n        r = requests.get(url)  # sync call in async function\n        results.append(r)\n    return results',
                 "no", "clear_negative"),
            Item("no_code_33",
                 'def process(items):\n    result = items[0]  # no bounds check\n    for i in range(len(items)):\n        result += items[i+1]  # off by one, index error',
                 "no", "clear_negative"),
            Item("no_code_34",
                 'class UserService:\n    def __init__(self):\n        self.db = Database("postgres://admin:admin@prod-db:5432/users")\n    def get_all(self):\n        return self.db.raw("SELECT * FROM users")  # returns all fields including hashed passwords',
                 "no", "clear_negative"),
            Item("no_code_35",
                 'def verify_webhook(request):\n    # signature verification disabled for testing\n    # if not verify_signature(request):\n    #     return 403\n    return process_webhook(request.json)',
                 "no", "clear_negative"),
            Item("no_code_36",
                 'def search(query):\n    return db.execute(f"SELECT * FROM products WHERE name LIKE \'%{query}%\'")',
                 "no", "clear_negative"),
            Item("no_code_37",
                 'app.config["SESSION_COOKIE_SECURE"] = False\napp.config["SESSION_COOKIE_HTTPONLY"] = False\napp.config["SESSION_COOKIE_SAMESITE"] = None',
                 "no", "clear_negative"),
            Item("no_code_38",
                 'def backup_db():\n    os.system("pg_dump prod_db > /tmp/backup.sql")\n    os.system("chmod 777 /tmp/backup.sql")',
                 "no", "clear_negative"),
            Item("no_code_39",
                 'def log_request(request):\n    logger.info(f"Headers: {dict(request.headers)}")  # logs auth tokens\n    logger.info(f"Body: {request.get_data()}")  # logs passwords',
                 "no", "clear_negative"),
            Item("no_code_40",
                 'jwt_secret = "secret"\ndef make_token(user_id, is_admin):\n    import jwt\n    return jwt.encode({"user": user_id, "admin": is_admin}, jwt_secret, algorithm="HS256")\n\ndef verify(token):\n    return jwt.decode(token, jwt_secret, algorithms=["HS256", "none"])  # allows none algorithm',
                 "no", "clear_negative"),
            Item("no_code_41",
                 'class Cache:\n    data = {}  # class-level mutable default, shared across instances\n    def set(self, k, v):\n        self.data[k] = v  # never expires, never evicts',
                 "no", "clear_negative"),
            Item("no_code_42",
                 'def upload(request):\n    data = request.json\n    filename = data["name"]  # no sanitization\n    with open(f"/uploads/{filename}", "wb") as f:\n        f.write(base64.b64decode(data["content"]))\n    os.chmod(f"/uploads/{filename}", 0o777)',
                 "no", "clear_negative"),
            Item("no_code_43",
                 'def reset_password(email):\n    new_password = "temporary123"\n    db.update_password(email, new_password)\n    send_email(email, f"Your new password is: {new_password}")  # plaintext password in email',
                 "no", "clear_negative"),
            Item("no_code_44",
                 'def connect_db():\n    retries = 0\n    while True:\n        try:\n            return psycopg2.connect(DSN)\n        except:\n            retries += 1\n            # no max retries, no backoff, no logging',
                 "no", "clear_negative"),
            Item("no_code_45",
                 'def render_template(template_name, user_data):\n    template = open(f"templates/{template_name}").read()\n    for key, value in user_data.items():\n        template = template.replace(f"{{{key}}}", str(value))  # DIY template engine, XSS',
                 "no", "clear_negative"),
            Item("no_code_46",
                 '@app.route("/api/data")\ndef get_data():\n    return jsonify(db.get_all_records())  # no pagination, no auth, returns everything',
                 "no", "clear_negative"),
            Item("no_code_47",
                 'def parse_xml(user_input):\n    from lxml import etree\n    parser = etree.XMLParser(resolve_entities=True)\n    return etree.fromstring(user_input, parser)  # XXE vulnerability',
                 "no", "clear_negative"),
            Item("no_code_48",
                 'def change_role(request):\n    user_id = request.form["user_id"]\n    new_role = request.form["role"]\n    db.execute(f"UPDATE users SET role=\'{new_role}\' WHERE id={user_id}")  # no CSRF, no auth, SQL injection',
                 "no", "clear_negative"),
            Item("no_code_49",
                 'ALLOWED_EXTENSIONS = None  # accept any file type\nMAX_UPLOAD_SIZE = None  # no size limit\ndef upload(file):\n    file.save(f"/var/www/public/{file.filename}")',
                 "no", "clear_negative"),
            Item("no_code_50",
                 'from Crypto.Cipher import DES\ndef encrypt(data, key):\n    cipher = DES.new(key, DES.MODE_ECB)  # DES is broken, ECB mode',
                 "no", "clear_negative"),
            Item("no_code_51",
                 'def authenticate(username, password):\n    user = db.find_user(username)\n    if user is None:\n        return "User not found"\n    if user.password != password:\n        return "Wrong password"\n    return "Success"\n    # different error messages = username enumeration',
                 "no", "clear_negative"),
            Item("no_code_52",
                 'def api_handler(request):\n    action = request.json["action"]\n    return getattr(db, action)(request.json["params"])  # arbitrary method call',
                 "no", "clear_negative"),
            Item("no_code_53",
                 'def generate_id():\n    global counter\n    counter += 1\n    return counter  # predictable IDs, race condition',
                 "no", "clear_negative"),
            Item("no_code_54",
                 'SSL_VERIFY = False\ndef call_api(url, data):\n    return requests.post(url, json=data, verify=SSL_VERIFY)  # disabled SSL verification',
                 "no", "clear_negative"),
            Item("no_code_55",
                 'def export_users():\n    users = db.get_all_users()\n    csv_data = "name,email,ssn,password_hash,address,phone\\n"\n    for u in users:\n        csv_data += f"{u.name},{u.email},{u.ssn},{u.password_hash},{u.address},{u.phone}\\n"\n    return Response(csv_data, mimetype="text/csv")  # exports PII including SSN',
                 "no", "clear_negative"),
        ]

    def get_context_items_yes(self) -> list[Item]:
        """Clearly good code — should always get 'yes'."""
        return [
            Item("yes_code_01",
                 'from typing import Optional\nfrom pydantic import BaseModel, EmailStr\n\nclass UserCreate(BaseModel):\n    email: EmailStr\n    name: str = Field(min_length=1, max_length=100)',
                 "yes", "clear_positive"),
            Item("yes_code_02",
                 'async def get_user(user_id: int, db: AsyncSession = Depends(get_db)) -> User:\n    user = await db.get(User, user_id)\n    if not user:\n        raise HTTPException(status_code=404, detail="User not found")\n    return user',
                 "yes", "clear_positive"),
            Item("yes_code_03",
                 'def hash_password(password: str) -> str:\n    import bcrypt\n    salt = bcrypt.gensalt(rounds=12)\n    return bcrypt.hashpw(password.encode(), salt).decode()',
                 "yes", "clear_positive"),
            Item("yes_code_04",
                 'import secrets\ndef generate_token(length: int = 32) -> str:\n    return secrets.token_urlsafe(length)',
                 "yes", "clear_positive"),
            Item("yes_code_05",
                 'from contextlib import asynccontextmanager\n\n@asynccontextmanager\nasync def get_db_session():\n    session = AsyncSession(engine)\n    try:\n        yield session\n        await session.commit()\n    except Exception:\n        await session.rollback()\n        raise\n    finally:\n        await session.close()',
                 "yes", "clear_positive"),
            Item("yes_code_06",
                 'from functools import lru_cache\nfrom pydantic_settings import BaseSettings\n\nclass Settings(BaseSettings):\n    database_url: str\n    secret_key: str\n    debug: bool = False\n    model_config = SettingsConfigDict(env_file=".env")\n\n@lru_cache\ndef get_settings() -> Settings:\n    return Settings()',
                 "yes", "clear_positive"),
            Item("yes_code_07",
                 'async def create_user(data: UserCreate, db: AsyncSession = Depends(get_db)) -> UserResponse:\n    existing = await db.execute(select(User).where(User.email == data.email))\n    if existing.scalar_one_or_none():\n        raise HTTPException(status_code=409, detail="Email already registered")\n    user = User(**data.model_dump())\n    db.add(user)\n    await db.commit()\n    await db.refresh(user)\n    return UserResponse.model_validate(user)',
                 "yes", "clear_positive"),
            Item("yes_code_08",
                 'import logging\nlogger = logging.getLogger(__name__)\n\ndef process_payment(amount: Decimal, user_id: int) -> PaymentResult:\n    logger.info("Processing payment", extra={"user_id": user_id, "amount": str(amount)})\n    try:\n        result = payment_gateway.charge(amount)\n        logger.info("Payment successful", extra={"user_id": user_id, "transaction_id": result.id})\n        return result\n    except PaymentError as e:\n        logger.error("Payment failed", extra={"user_id": user_id, "error": str(e)})\n        raise',
                 "yes", "clear_positive"),
            Item("yes_code_09",
                 'from pathlib import Path\n\ndef safe_read_file(base_dir: Path, filename: str) -> str:\n    safe_path = (base_dir / filename).resolve()\n    if not safe_path.is_relative_to(base_dir.resolve()):\n        raise ValueError("Path traversal detected")\n    return safe_path.read_text()',
                 "yes", "clear_positive"),
            Item("yes_code_10",
                 'from sqlalchemy import select\n\nasync def search_products(query: str, db: AsyncSession) -> list[Product]:\n    stmt = select(Product).where(Product.name.ilike(f"%{query}%")).limit(50)\n    result = await db.execute(stmt)\n    return result.scalars().all()',
                 "yes", "clear_positive"),
            Item("yes_code_11",
                 'from fastapi import Depends, HTTPException, status\nfrom fastapi.security import OAuth2PasswordBearer\n\noauth2_scheme = OAuth2PasswordBearer(tokenUrl="token")\n\nasync def get_current_user(token: str = Depends(oauth2_scheme)) -> User:\n    credentials_exception = HTTPException(status_code=status.HTTP_401_UNAUTHORIZED)\n    try:\n        payload = jwt.decode(token, settings.secret_key, algorithms=["HS256"])\n        user_id: int = payload.get("sub")\n        if user_id is None:\n            raise credentials_exception\n    except JWTError:\n        raise credentials_exception\n    user = await get_user(user_id)\n    if user is None:\n        raise credentials_exception\n    return user',
                 "yes", "clear_positive"),
            Item("yes_code_12",
                 'from typing import Annotated\nfrom fastapi import Query\n\nasync def list_items(\n    skip: Annotated[int, Query(ge=0)] = 0,\n    limit: Annotated[int, Query(ge=1, le=100)] = 20,\n    db: AsyncSession = Depends(get_db)\n) -> PaginatedResponse[Item]:\n    total = await db.scalar(select(func.count(Item.id)))\n    items = await db.execute(select(Item).offset(skip).limit(limit))\n    return PaginatedResponse(items=items.scalars().all(), total=total)',
                 "yes", "clear_positive"),
            Item("yes_code_13",
                 'import httpx\nfrom tenacity import retry, stop_after_attempt, wait_exponential\n\n@retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, max=10))\nasync def fetch_external_data(url: str) -> dict:\n    async with httpx.AsyncClient(timeout=10.0) as client:\n        response = await client.get(url)\n        response.raise_for_status()\n        return response.json()',
                 "yes", "clear_positive"),
            Item("yes_code_14",
                 'from datetime import datetime, timedelta\nfrom jose import jwt\n\ndef create_access_token(data: dict, expires_delta: timedelta = timedelta(minutes=15)) -> str:\n    to_encode = data.copy()\n    expire = datetime.utcnow() + expires_delta\n    to_encode.update({"exp": expire, "iat": datetime.utcnow()})\n    return jwt.encode(to_encode, settings.secret_key, algorithm="HS256")',
                 "yes", "clear_positive"),
            Item("yes_code_15",
                 'from fastapi import UploadFile\nimport magic\n\nALLOWED_TYPES = {"image/jpeg", "image/png", "image/webp"}\nMAX_SIZE = 5 * 1024 * 1024  # 5MB\n\nasync def upload_image(file: UploadFile) -> str:\n    content = await file.read()\n    if len(content) > MAX_SIZE:\n        raise HTTPException(413, "File too large")\n    mime = magic.from_buffer(content, mime=True)\n    if mime not in ALLOWED_TYPES:\n        raise HTTPException(415, "Unsupported file type")\n    filename = f"{uuid4().hex}.{mime.split(\"/\")[1]}"\n    path = UPLOAD_DIR / filename\n    path.write_bytes(content)\n    return filename',
                 "yes", "clear_positive"),
            Item("yes_code_16",
                 'class RateLimiter:\n    def __init__(self, max_requests: int, window_seconds: int):\n        self.max_requests = max_requests\n        self.window = window_seconds\n        self._requests: dict[str, list[float]] = {}\n\n    def is_allowed(self, key: str) -> bool:\n        now = time.time()\n        self._requests.setdefault(key, [])\n        self._requests[key] = [t for t in self._requests[key] if now - t < self.window]\n        if len(self._requests[key]) >= self.max_requests:\n            return False\n        self._requests[key].append(now)\n        return True',
                 "yes", "clear_positive"),
            Item("yes_code_17",
                 'from fastapi.middleware.cors import CORSMiddleware\n\napp.add_middleware(\n    CORSMiddleware,\n    allow_origins=["https://myapp.com", "https://staging.myapp.com"],\n    allow_credentials=True,\n    allow_methods=["GET", "POST", "PUT", "DELETE"],\n    allow_headers=["Authorization", "Content-Type"],\n)',
                 "yes", "clear_positive"),
            Item("yes_code_18",
                 'from enum import Enum\nfrom pydantic import BaseModel\n\nclass OrderStatus(str, Enum):\n    PENDING = "pending"\n    CONFIRMED = "confirmed"\n    SHIPPED = "shipped"\n    DELIVERED = "delivered"\n\nclass OrderUpdate(BaseModel):\n    status: OrderStatus\n\n    def validate_transition(self, current: OrderStatus) -> bool:\n        valid = {\n            OrderStatus.PENDING: {OrderStatus.CONFIRMED},\n            OrderStatus.CONFIRMED: {OrderStatus.SHIPPED},\n            OrderStatus.SHIPPED: {OrderStatus.DELIVERED},\n        }\n        return self.status in valid.get(current, set())',
                 "yes", "clear_positive"),
            Item("yes_code_19",
                 'async def healthcheck() -> dict:\n    checks = {}\n    try:\n        await db.execute(text("SELECT 1"))\n        checks["database"] = "ok"\n    except Exception:\n        checks["database"] = "error"\n    try:\n        await redis.ping()\n        checks["cache"] = "ok"\n    except Exception:\n        checks["cache"] = "error"\n    status = "healthy" if all(v == "ok" for v in checks.values()) else "unhealthy"\n    return {"status": status, "checks": checks}',
                 "yes", "clear_positive"),
            Item("yes_code_20",
                 'from contextlib import contextmanager\nimport psycopg2\n\n@contextmanager\ndef get_cursor(dsn: str):\n    conn = psycopg2.connect(dsn)\n    try:\n        with conn.cursor() as cur:\n            yield cur\n        conn.commit()\n    except Exception:\n        conn.rollback()\n        raise\n    finally:\n        conn.close()',
                 "yes", "clear_positive"),
            Item("yes_code_21",
                 'async def batch_process(items: list[Item], batch_size: int = 100) -> list[Result]:\n    results = []\n    for i in range(0, len(items), batch_size):\n        batch = items[i:i + batch_size]\n        batch_results = await asyncio.gather(\n            *[process_item(item) for item in batch],\n            return_exceptions=True\n        )\n        for item, result in zip(batch, batch_results):\n            if isinstance(result, Exception):\n                logger.error(f"Failed to process item {item.id}: {result}")\n            else:\n                results.append(result)\n    return results',
                 "yes", "clear_positive"),
            Item("yes_code_22",
                 'class CircuitBreaker:\n    def __init__(self, failure_threshold: int = 5, recovery_timeout: float = 30.0):\n        self.failure_threshold = failure_threshold\n        self.recovery_timeout = recovery_timeout\n        self._failures = 0\n        self._last_failure_time: float | None = None\n        self._state = "closed"\n\n    def call(self, func, *args, **kwargs):\n        if self._state == "open":\n            if time.time() - self._last_failure_time > self.recovery_timeout:\n                self._state = "half-open"\n            else:\n                raise CircuitOpenError()\n        try:\n            result = func(*args, **kwargs)\n            self._failures = 0\n            self._state = "closed"\n            return result\n        except Exception as e:\n            self._failures += 1\n            self._last_failure_time = time.time()\n            if self._failures >= self.failure_threshold:\n                self._state = "open"\n            raise',
                 "yes", "clear_positive"),
            Item("yes_code_23",
                 'def sanitize_filename(filename: str) -> str:\n    stem = Path(filename).stem\n    suffix = Path(filename).suffix.lower()\n    if suffix not in ALLOWED_EXTENSIONS:\n        raise ValueError(f"Extension {suffix} not allowed")\n    safe_stem = re.sub(r"[^\\w\\-]", "_", stem)[:100]\n    return f"{safe_stem}_{uuid4().hex[:8]}{suffix}"',
                 "yes", "clear_positive"),
            Item("yes_code_24",
                 'from functools import wraps\nimport time\n\ndef timed(func):\n    @wraps(func)\n    async def wrapper(*args, **kwargs):\n        start = time.perf_counter()\n        try:\n            return await func(*args, **kwargs)\n        finally:\n            elapsed = time.perf_counter() - start\n            logger.info(f"{func.__name__} took {elapsed:.3f}s")\n    return wrapper',
                 "yes", "clear_positive"),
            Item("yes_code_25",
                 'from dataclasses import dataclass\nfrom typing import Generic, TypeVar\n\nT = TypeVar("T")\n\n@dataclass\nclass Result(Generic[T]):\n    value: T | None = None\n    error: str | None = None\n    \n    @property\n    def is_ok(self) -> bool:\n        return self.error is None\n    \n    @classmethod\n    def ok(cls, value: T) -> "Result[T]":\n        return cls(value=value)\n    \n    @classmethod\n    def fail(cls, error: str) -> "Result[T]":\n        return cls(error=error)',
                 "yes", "clear_positive"),
            Item("yes_code_26",
                 'async def get_or_create(\n    db: AsyncSession, model: type[Base], defaults: dict, **kwargs\n) -> tuple[Base, bool]:\n    stmt = select(model).filter_by(**kwargs)\n    instance = (await db.execute(stmt)).scalar_one_or_none()\n    if instance:\n        return instance, False\n    instance = model(**kwargs, **defaults)\n    db.add(instance)\n    await db.flush()\n    return instance, True',
                 "yes", "clear_positive"),
            Item("yes_code_27",
                 'import structlog\n\nlogger = structlog.get_logger()\n\nasync def process_order(order_id: str, user_id: str) -> OrderResult:\n    log = logger.bind(order_id=order_id, user_id=user_id)\n    log.info("processing_order_started")\n    try:\n        result = await payment_service.charge(order_id)\n        log.info("payment_charged", transaction_id=result.transaction_id)\n        await inventory_service.reserve(order_id)\n        log.info("inventory_reserved")\n        return OrderResult(status="success")\n    except PaymentError as e:\n        log.warning("payment_failed", reason=str(e))\n        raise',
                 "yes", "clear_positive"),
            Item("yes_code_28",
                 'from datetime import datetime, timezone\n\ndef utc_now() -> datetime:\n    return datetime.now(timezone.utc)\n\nclass TimestampMixin:\n    created_at: Mapped[datetime] = mapped_column(default=utc_now)\n    updated_at: Mapped[datetime] = mapped_column(default=utc_now, onupdate=utc_now)',
                 "yes", "clear_positive"),
            Item("yes_code_29",
                 'from typing import AsyncIterator\n\nasync def stream_large_file(path: Path, chunk_size: int = 8192) -> AsyncIterator[bytes]:\n    async with aiofiles.open(path, "rb") as f:\n        while chunk := await f.read(chunk_size):\n            yield chunk',
                 "yes", "clear_positive"),
            Item("yes_code_30",
                 'class Pagination:\n    def __init__(self, page: int = 1, per_page: int = 20, max_per_page: int = 100):\n        self.page = max(1, page)\n        self.per_page = min(max(1, per_page), max_per_page)\n    \n    @property\n    def offset(self) -> int:\n        return (self.page - 1) * self.per_page\n    \n    def paginate(self, query):\n        return query.offset(self.offset).limit(self.per_page)',
                 "yes", "clear_positive"),
            # Extra items for longer contexts
            Item("yes_code_31",
                 'def validate_email(email: str) -> bool:\n    import re\n    pattern = r"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$"\n    return bool(re.match(pattern, email))',
                 "yes", "clear_positive"),
            Item("yes_code_32",
                 'async def with_timeout(coro, timeout_seconds: float = 30.0):\n    try:\n        return await asyncio.wait_for(coro, timeout=timeout_seconds)\n    except asyncio.TimeoutError:\n        logger.warning(f"Operation timed out after {timeout_seconds}s")\n        raise HTTPException(504, "Gateway timeout")',
                 "yes", "clear_positive"),
            Item("yes_code_33",
                 'class Config:\n    REQUIRED_ENV_VARS = ["DATABASE_URL", "SECRET_KEY", "REDIS_URL"]\n    \n    @classmethod\n    def validate(cls) -> None:\n        missing = [var for var in cls.REQUIRED_ENV_VARS if not os.getenv(var)]\n        if missing:\n            raise EnvironmentError(f"Missing required env vars: {missing}")',
                 "yes", "clear_positive"),
            Item("yes_code_34",
                 'from weakref import WeakValueDictionary\n\nclass ConnectionPool:\n    def __init__(self, max_size: int = 10):\n        self._pool: list = []\n        self._size = 0\n        self._max_size = max_size\n        self._lock = asyncio.Lock()\n    \n    async def acquire(self):\n        async with self._lock:\n            if self._pool:\n                return self._pool.pop()\n            if self._size < self._max_size:\n                self._size += 1\n                return await self._create_connection()\n            raise PoolExhaustedError()',
                 "yes", "clear_positive"),
            Item("yes_code_35",
                 'def retry_with_backoff(max_retries: int = 3, base_delay: float = 1.0):\n    def decorator(func):\n        @wraps(func)\n        async def wrapper(*args, **kwargs):\n            for attempt in range(max_retries):\n                try:\n                    return await func(*args, **kwargs)\n                except TransientError as e:\n                    if attempt == max_retries - 1:\n                        raise\n                    delay = base_delay * (2 ** attempt)\n                    logger.warning(f"Retry {attempt+1}/{max_retries} after {delay}s: {e}")\n                    await asyncio.sleep(delay)\n        return wrapper\n    return decorator',
                 "yes", "clear_positive"),
            Item("yes_code_36",
                 'async def graceful_shutdown(app):\n    logger.info("Shutting down gracefully...")\n    app.state.accepting_requests = False\n    await asyncio.sleep(5)  # drain in-flight requests\n    await app.state.db_pool.close()\n    await app.state.redis.close()\n    logger.info("Shutdown complete")',
                 "yes", "clear_positive"),
            Item("yes_code_37",
                 'class IdempotencyMiddleware:\n    async def __call__(self, request, call_next):\n        key = request.headers.get("Idempotency-Key")\n        if not key:\n            return await call_next(request)\n        cached = await redis.get(f"idempotency:{key}")\n        if cached:\n            return JSONResponse(json.loads(cached))\n        response = await call_next(request)\n        if response.status_code < 400:\n            body = b"".join([chunk async for chunk in response.body_iterator])\n            await redis.setex(f"idempotency:{key}", 86400, body)\n            return Response(content=body, status_code=response.status_code)\n        return response',
                 "yes", "clear_positive"),
            Item("yes_code_38",
                 'from hmac import compare_digest\nimport hashlib\nimport hmac\n\ndef verify_webhook_signature(payload: bytes, signature: str, secret: str) -> bool:\n    expected = hmac.new(secret.encode(), payload, hashlib.sha256).hexdigest()\n    return compare_digest(f"sha256={expected}", signature)',
                 "yes", "clear_positive"),
            Item("yes_code_39",
                 'class EventBus:\n    def __init__(self):\n        self._handlers: dict[str, list[Callable]] = defaultdict(list)\n    \n    def subscribe(self, event_type: str, handler: Callable) -> None:\n        self._handlers[event_type].append(handler)\n    \n    async def publish(self, event_type: str, data: dict) -> None:\n        for handler in self._handlers.get(event_type, []):\n            try:\n                await handler(data)\n            except Exception:\n                logger.exception(f"Handler failed for {event_type}")',
                 "yes", "clear_positive"),
            Item("yes_code_40",
                 'def mask_pii(data: dict, fields: set[str] = {"ssn", "credit_card", "password"}) -> dict:\n    masked = {}\n    for key, value in data.items():\n        if key in fields:\n            masked[key] = "***REDACTED***"\n        elif isinstance(value, dict):\n            masked[key] = mask_pii(value, fields)\n        else:\n            masked[key] = value\n    return masked',
                 "yes", "clear_positive"),
            Item("yes_code_41",
                 'from collections.abc import AsyncIterator\n\nasync def paginate_query(\n    query, session: AsyncSession, page_size: int = 100\n) -> AsyncIterator[list]:\n    offset = 0\n    while True:\n        result = await session.execute(query.offset(offset).limit(page_size))\n        batch = result.scalars().all()\n        if not batch:\n            break\n        yield batch\n        offset += page_size',
                 "yes", "clear_positive"),
            Item("yes_code_42",
                 'from pydantic import BaseModel, model_validator\n\nclass DateRange(BaseModel):\n    start: date\n    end: date\n    \n    @model_validator(mode="after")\n    def validate_range(self) -> "DateRange":\n        if self.end < self.start:\n            raise ValueError("end must be after start")\n        if (self.end - self.start).days > 365:\n            raise ValueError("range cannot exceed 1 year")\n        return self',
                 "yes", "clear_positive"),
            Item("yes_code_43",
                 'async def atomic_transfer(\n    db: AsyncSession, from_id: int, to_id: int, amount: Decimal\n) -> None:\n    async with db.begin():\n        sender = await db.get(Account, from_id, with_for_update=True)\n        receiver = await db.get(Account, to_id, with_for_update=True)\n        if sender.balance < amount:\n            raise InsufficientFunds()\n        sender.balance -= amount\n        receiver.balance += amount',
                 "yes", "clear_positive"),
            Item("yes_code_44",
                 'from cachetools import TTLCache\nfrom threading import Lock\n\nclass ThreadSafeCache:\n    def __init__(self, maxsize: int = 1000, ttl: int = 300):\n        self._cache = TTLCache(maxsize=maxsize, ttl=ttl)\n        self._lock = Lock()\n    \n    def get(self, key: str) -> Any | None:\n        with self._lock:\n            return self._cache.get(key)\n    \n    def set(self, key: str, value: Any) -> None:\n        with self._lock:\n            self._cache[key] = value',
                 "yes", "clear_positive"),
            Item("yes_code_45",
                 'class CSPMiddleware:\n    async def __call__(self, request, call_next):\n        response = await call_next(request)\n        response.headers["Content-Security-Policy"] = (\n            "default-src \'self\'; "\n            "script-src \'self\'; "\n            "style-src \'self\' \'unsafe-inline\'; "\n            "img-src \'self\' data: https:; "\n            "font-src \'self\'; "\n            "connect-src \'self\' https://api.myapp.com"\n        )\n        return response',
                 "yes", "clear_positive"),
            Item("yes_code_46",
                 'async def safe_json_parse(data: bytes, max_size: int = 1_000_000) -> dict:\n    if len(data) > max_size:\n        raise ValueError(f"Payload too large: {len(data)} bytes")\n    try:\n        return json.loads(data)\n    except json.JSONDecodeError as e:\n        raise ValueError(f"Invalid JSON: {e}")',
                 "yes", "clear_positive"),
            Item("yes_code_47",
                 'from abc import ABC, abstractmethod\n\nclass NotificationService(ABC):\n    @abstractmethod\n    async def send(self, recipient: str, message: str) -> bool: ...\n\nclass EmailNotification(NotificationService):\n    async def send(self, recipient: str, message: str) -> bool:\n        async with aiosmtplib.SMTP(hostname=SMTP_HOST, port=SMTP_PORT, use_tls=True) as smtp:\n            msg = MIMEText(message)\n            msg["To"] = recipient\n            msg["From"] = FROM_ADDRESS\n            await smtp.send_message(msg)\n            return True',
                 "yes", "clear_positive"),
            Item("yes_code_48",
                 'def constant_time_compare(a: str, b: str) -> bool:\n    """Prevent timing attacks on string comparison."""\n    from hmac import compare_digest\n    return compare_digest(a.encode(), b.encode())',
                 "yes", "clear_positive"),
            Item("yes_code_49",
                 'from asyncio import Semaphore\n\nclass ThrottledClient:\n    def __init__(self, max_concurrent: int = 10):\n        self._semaphore = Semaphore(max_concurrent)\n        self._client = httpx.AsyncClient(timeout=30.0)\n    \n    async def get(self, url: str) -> httpx.Response:\n        async with self._semaphore:\n            return await self._client.get(url)',
                 "yes", "clear_positive"),
            Item("yes_code_50",
                 'class FeatureFlag:\n    def __init__(self, redis_client):\n        self._redis = redis_client\n    \n    async def is_enabled(self, flag: str, user_id: str | None = None) -> bool:\n        global_flag = await self._redis.get(f"ff:{flag}")\n        if global_flag == "disabled":\n            return False\n        if global_flag == "enabled":\n            return True\n        if user_id:\n            return await self._redis.sismember(f"ff:{flag}:users", user_id)\n        return False',
                 "yes", "clear_positive"),
            Item("yes_code_51",
                 'class InputSanitizer:\n    @staticmethod\n    def strip_html(text: str) -> str:\n        import bleach\n        return bleach.clean(text, tags=[], strip=True)\n    \n    @staticmethod\n    def normalize_whitespace(text: str) -> str:\n        return " ".join(text.split())\n    \n    @staticmethod\n    def truncate(text: str, max_length: int = 1000) -> str:\n        return text[:max_length] if len(text) > max_length else text',
                 "yes", "clear_positive"),
            Item("yes_code_52",
                 'async def health_check_dependencies() -> dict[str, str]:\n    async def check(name: str, coro) -> tuple[str, str]:\n        try:\n            await asyncio.wait_for(coro, timeout=5.0)\n            return name, "healthy"\n        except Exception as e:\n            return name, f"unhealthy: {type(e).__name__}"\n    \n    checks = await asyncio.gather(\n        check("database", db.execute(text("SELECT 1"))),\n        check("redis", redis.ping()),\n        check("storage", storage.head_bucket()),\n    )\n    return dict(checks)',
                 "yes", "clear_positive"),
            Item("yes_code_53",
                 'from cryptography.fernet import Fernet\n\nclass FieldEncryption:\n    def __init__(self, key: bytes):\n        self._fernet = Fernet(key)\n    \n    def encrypt(self, plaintext: str) -> str:\n        return self._fernet.encrypt(plaintext.encode()).decode()\n    \n    def decrypt(self, ciphertext: str) -> str:\n        return self._fernet.decrypt(ciphertext.encode()).decode()',
                 "yes", "clear_positive"),
            Item("yes_code_54",
                 'from slowapi import Limiter\nfrom slowapi.util import get_remote_address\n\nlimiter = Limiter(key_func=get_remote_address)\n\n@app.post("/api/login")\n@limiter.limit("5/minute")\nasync def login(request: Request, credentials: LoginRequest):\n    return await auth_service.authenticate(credentials)',
                 "yes", "clear_positive"),
            Item("yes_code_55",
                 'class AuditLog:\n    def __init__(self, db: AsyncSession):\n        self._db = db\n    \n    async def log(self, user_id: str, action: str, resource: str, details: dict | None = None) -> None:\n        entry = AuditEntry(\n            user_id=user_id,\n            action=action,\n            resource=resource,\n            details=mask_pii(details or {}),\n            timestamp=utc_now(),\n            ip_address=get_client_ip(),\n        )\n        self._db.add(entry)\n        await self._db.flush()',
                 "yes", "clear_positive"),
        ]

    def get_test_items(self) -> list[Item]:
        """Test items across three categories."""
        return [
            # CLEAR POSITIVE — obviously good code
            Item("test_code_cp_01",
                 'from pathlib import Path\nfrom uuid import uuid4\n\ndef save_upload(content: bytes, extension: str) -> Path:\n    if extension not in {".jpg", ".png", ".pdf"}:\n        raise ValueError("Unsupported format")\n    filename = f"{uuid4().hex}{extension}"\n    path = UPLOAD_DIR / filename\n    path.write_bytes(content)\n    return path',
                 "yes", "clear_positive"),
            Item("test_code_cp_02",
                 'async def get_user_by_email(email: str, db: AsyncSession) -> User | None:\n    stmt = select(User).where(User.email == email)\n    result = await db.execute(stmt)\n    return result.scalar_one_or_none()',
                 "yes", "clear_positive"),
            Item("test_code_cp_03",
                 'import bcrypt\n\ndef verify_password(plain_password: str, hashed_password: str) -> bool:\n    return bcrypt.checkpw(plain_password.encode(), hashed_password.encode())',
                 "yes", "clear_positive"),
            Item("test_code_cp_04",
                 'from pydantic import BaseModel, Field\n\nclass CreateOrder(BaseModel):\n    product_id: int = Field(gt=0)\n    quantity: int = Field(ge=1, le=100)\n    shipping_address: str = Field(min_length=10, max_length=500)',
                 "yes", "clear_positive"),
            Item("test_code_cp_05",
                 'async def delete_user(user_id: int, current_user: User = Depends(get_current_admin)) -> None:\n    user = await db.get(User, user_id)\n    if not user:\n        raise HTTPException(404)\n    await db.delete(user)\n    await db.commit()\n    logger.info("user_deleted", deleted_id=user_id, by=current_user.id)',
                 "yes", "clear_positive"),
            Item("test_code_cp_06",
                 'from decimal import Decimal\n\ndef calculate_tax(subtotal: Decimal, tax_rate: Decimal) -> Decimal:\n    if subtotal < 0:\n        raise ValueError("Subtotal cannot be negative")\n    if not (0 <= tax_rate <= 1):\n        raise ValueError("Tax rate must be between 0 and 1")\n    return (subtotal * tax_rate).quantize(Decimal("0.01"))',
                 "yes", "clear_positive"),
            Item("test_code_cp_07",
                 'class DatabaseMigration:\n    def __init__(self, db: AsyncSession):\n        self._db = db\n    \n    async def migrate(self) -> None:\n        async with self._db.begin():\n            version = await self._get_current_version()\n            pending = [m for m in MIGRATIONS if m.version > version]\n            for migration in sorted(pending, key=lambda m: m.version):\n                await migration.up(self._db)\n                await self._set_version(migration.version)\n                logger.info(f"Applied migration {migration.version}")',
                 "yes", "clear_positive"),

            # AMBIGUOUS
            Item("test_code_amb_01",
                 'def process_data(items):\n    results = []\n    for item in items:\n        try:\n            results.append(transform(item))\n        except Exception:\n            continue  # skip failed items silently\n    return results',
                 "yes", "ambiguous"),
            Item("test_code_amb_02",
                 'def get_config():\n    config = {\n        "debug": os.getenv("DEBUG", "false").lower() == "true",\n        "port": int(os.getenv("PORT", "8080")),\n        "host": os.getenv("HOST", "0.0.0.0"),\n    }\n    return config',
                 "yes", "ambiguous"),
            Item("test_code_amb_03",
                 'def cache_result(ttl=300):\n    cache = {}\n    def decorator(func):\n        def wrapper(*args):\n            key = str(args)\n            if key in cache and time.time() - cache[key][1] < ttl:\n                return cache[key][0]\n            result = func(*args)\n            cache[key] = (result, time.time())\n            return result\n        return wrapper\n    return decorator',
                 "yes", "ambiguous"),
            Item("test_code_amb_04",
                 'def parse_user_agent(ua_string: str) -> dict:\n    parts = ua_string.split("/")\n    return {\n        "browser": parts[0] if parts else "unknown",\n        "version": parts[1] if len(parts) > 1 else "unknown"\n    }',
                 "yes", "ambiguous"),
            Item("test_code_amb_05",
                 'class SimpleQueue:\n    def __init__(self, max_size=1000):\n        self._items = []\n        self._max_size = max_size\n    \n    def push(self, item):\n        if len(self._items) >= self._max_size:\n            self._items.pop(0)\n        self._items.append(item)\n    \n    def pop(self):\n        return self._items.pop(0) if self._items else None',
                 "yes", "ambiguous"),
            Item("test_code_amb_06",
                 'import json\nimport gzip\n\ndef compress_and_store(data: dict, filepath: str) -> None:\n    json_bytes = json.dumps(data).encode()\n    with gzip.open(filepath, "wb") as f:\n        f.write(json_bytes)',
                 "yes", "ambiguous"),
            Item("test_code_amb_07",
                 'def flatten(nested: list) -> list:\n    result = []\n    for item in nested:\n        if isinstance(item, list):\n            result.extend(flatten(item))\n        else:\n            result.append(item)\n    return result',
                 "yes", "ambiguous"),

            # CLEAR NEGATIVE — obviously bad code
            Item("test_code_cn_01",
                 'def admin_panel(request):\n    if request.args.get("admin") == "true":\n        return get_all_users_with_passwords()',
                 "no", "clear_negative"),
            Item("test_code_cn_02",
                 'DATABASE_PASSWORD = "super_secret_prod_password_2024"\nAPI_SECRET = "sk-live-abcdef123456"\nAWS_SECRET_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"',
                 "no", "clear_negative"),
            Item("test_code_cn_03",
                 'def search_users(name):\n    return db.execute(f"SELECT * FROM users WHERE name = \'{name}\'")',
                 "no", "clear_negative"),
            Item("test_code_cn_04",
                 'def run_user_code(request):\n    code = request.json["code"]\n    result = eval(code)\n    return {"result": result}',
                 "no", "clear_negative"),
            Item("test_code_cn_05",
                 'def verify_token(token):\n    try:\n        return jwt.decode(token, options={"verify_signature": False})\n    except:\n        return None',
                 "no", "clear_negative"),
            Item("test_code_cn_06",
                 'import hashlib\ndef store_password(password):\n    hashed = hashlib.sha1(password.encode()).hexdigest()\n    db.save(hashed)  # SHA1, no salt',
                 "no", "clear_negative"),
            Item("test_code_cn_07",
                 'def download(request):\n    path = request.args["file"]\n    return send_file(f"/var/data/{path}")  # path traversal, no auth',
                 "no", "clear_negative"),
        ]
