"""Fixed non-evaluative Q&A pairs used as filler turns in the
neutral-filler control experiment.

The reviewer flagged that the main experiment's neutral arm uses
*evaluative* filler (balanced 50/50 yes/no judgments on other items),
so the comparison ``baseline (no history) vs.\\ neutral arm`` cannot
distinguish a polarity-of-history effect from a
presence-of-evaluative-history effect.

This module supplies non-evaluative filler: short factual Q&A pairs
on geography, science, history, language, and trivia. None contain
"yes"/"no" tokens, evaluative adjectives ("good", "bad"), or
recommendation language. The list is fixed (not generated at runtime)
for full reproducibility.

Length is matched roughly to the main experiment's evaluative filler
(typical question 6--12 words; answer 3--20 words).
"""
from __future__ import annotations

FILLER_PAIRS: list[tuple[str, str]] = [
    ("What is the capital of France?", "Paris."),
    ("Who painted the Mona Lisa?", "Leonardo da Vinci."),
    ("What is the chemical symbol for gold?", "Au."),
    ("In which year did World War II end?", "1945."),
    ("What is the largest planet in our solar system?", "Jupiter."),
    ("Who wrote Hamlet?", "William Shakespeare."),
    ("What is the boiling point of water at sea level in Celsius?", "100."),
    ("What is the longest river in the world?", "The Nile."),
    ("In which continent is the Sahara Desert?", "Africa."),
    ("What is the speed of light in a vacuum, in metres per second?", "Approximately 299,792,458."),
    ("Who developed the theory of general relativity?", "Albert Einstein."),
    ("What is the smallest country in the world by area?", "Vatican City."),
    ("Which planet is known as the Red Planet?", "Mars."),
    ("What is the official language of Brazil?", "Portuguese."),
    ("What is the freezing point of water in Fahrenheit?", "32."),
    ("Who discovered penicillin?", "Alexander Fleming."),
    ("What is the tallest mountain in the world?", "Mount Everest."),
    ("In which year was the Eiffel Tower completed?", "1889."),
    ("What is the currency of Japan?", "The yen."),
    ("Who composed the Fifth Symphony?", "Ludwig van Beethoven."),
    ("What is the largest ocean on Earth?", "The Pacific Ocean."),
    ("Which gas do plants absorb during photosynthesis?", "Carbon dioxide."),
    ("In which country is the city of Istanbul located?", "Turkey."),
    ("What is the chemical formula for water?", "H2O."),
    ("Who wrote the novel '1984'?", "George Orwell."),
    ("What is the smallest unit of life?", "The cell."),
    ("Which country has the most islands?", "Sweden."),
    ("What is the largest mammal in the world?", "The blue whale."),
    ("In which year did the Berlin Wall fall?", "1989."),
    ("What is the hardest natural substance on Earth?", "Diamond."),
    ("Which element has the atomic number 1?", "Hydrogen."),
    ("Who was the first person to walk on the Moon?", "Neil Armstrong."),
    ("What is the capital of Australia?", "Canberra."),
    ("Which sea separates Europe from Africa?", "The Mediterranean."),
    ("In which year did the Titanic sink?", "1912."),
    ("What is the largest desert in the world?", "Antarctica."),
    ("Who painted the ceiling of the Sistine Chapel?", "Michelangelo."),
    ("What is the deepest part of the ocean?", "The Mariana Trench."),
    ("Which language has the most native speakers?", "Mandarin Chinese."),
    ("What is the currency of the United Kingdom?", "The pound sterling."),
    ("Who wrote 'The Origin of Species'?", "Charles Darwin."),
    ("Which planet is closest to the Sun?", "Mercury."),
    ("What is the longest bone in the human body?", "The femur."),
    ("In which country was the printing press invented?", "Germany."),
    ("Who was the first President of the United States?", "George Washington."),
    ("What is the chemical symbol for sodium?", "Na."),
    ("Which is the smallest continent?", "Australia."),
    ("In which year did humans first land on the Moon?", "1969."),
    ("What is the official language of Egypt?", "Arabic."),
    ("Who wrote 'War and Peace'?", "Leo Tolstoy."),
    ("What is the largest country by area?", "Russia."),
    ("Which metal is liquid at room temperature?", "Mercury."),
    ("In which city is the Colosseum?", "Rome."),
    ("Who invented the telephone?", "Alexander Graham Bell."),
    ("What is the most abundant gas in Earth's atmosphere?", "Nitrogen."),
    ("Which river flows through London?", "The Thames."),
    ("What is the capital of Canada?", "Ottawa."),
    ("Who painted 'The Starry Night'?", "Vincent van Gogh."),
    ("What is the chemical symbol for iron?", "Fe."),
    ("In which year did the French Revolution begin?", "1789."),
    ("Which is the largest island in the Mediterranean?", "Sicily."),
    ("Who wrote 'Pride and Prejudice'?", "Jane Austen."),
    ("What is the capital of South Korea?", "Seoul."),
    ("Which planet has the most moons?", "Saturn."),
    ("In which year was the United Nations founded?", "1945."),
    ("What is the chemical symbol for potassium?", "K."),
    ("Who composed 'The Four Seasons'?", "Antonio Vivaldi."),
    ("What is the official language of Argentina?", "Spanish."),
    ("Which mountain range separates Europe from Asia?", "The Ural Mountains."),
    ("In which year did Christopher Columbus reach the Americas?", "1492."),
    ("Who was the first woman to win a Nobel Prize?", "Marie Curie."),
    ("What is the longest mountain range in the world?", "The Andes."),
    ("Which country gifted the Statue of Liberty to the United States?", "France."),
    ("What is the chemical symbol for silver?", "Ag."),
    ("Who discovered the law of gravity?", "Isaac Newton."),
    ("What is the most populous country in the world?", "India, as of recent estimates."),
    ("In which year was the European Union founded by the Maastricht Treaty?", "1992."),
    ("Which city hosted the first modern Olympic Games?", "Athens."),
    ("What is the capital of Norway?", "Oslo."),
    ("Who painted 'Guernica'?", "Pablo Picasso."),
    ("What is the chemical symbol for lead?", "Pb."),
    ("In which year did the American Civil War end?", "1865."),
    ("Which planet has rings made primarily of ice particles?", "Saturn."),
    ("Who wrote 'Don Quixote'?", "Miguel de Cervantes."),
    ("What is the smallest bone in the human body?", "The stapes."),
    ("Which strait separates Spain from Morocco?", "The Strait of Gibraltar."),
    ("In which year was the printing press developed by Gutenberg?", "Around 1440."),
    ("What is the capital of Egypt?", "Cairo."),
    ("Who composed 'Carmen'?", "Georges Bizet."),
    ("What is the official language of Iran?", "Persian, also called Farsi."),
    ("Which country is home to the Great Barrier Reef?", "Australia."),
    ("In which year was the personal computer IBM PC released?", "1981."),
    ("Who was the first person to circumnavigate the globe?", "Ferdinand Magellan's expedition, completed by Juan Sebastian Elcano."),
    ("What is the capital of Sweden?", "Stockholm."),
    ("Which planet is known for its great red spot?", "Jupiter."),
    ("Who wrote 'The Iliad'?", "Homer."),
    ("What is the chemical symbol for copper?", "Cu."),
    ("In which year was the first iPhone released?", "2007."),
    ("Which river is the longest in South America?", "The Amazon."),
    ("What is the capital of Portugal?", "Lisbon."),
    ("Who painted 'The Persistence of Memory'?", "Salvador Dali."),
    ("What is the most spoken language in the world by total speakers?", "English."),
]

assert len(FILLER_PAIRS) >= 50, f"need at least 50 pairs, got {len(FILLER_PAIRS)}"
